### ISSUE TITLE
Define release process for each asset

### ISSUE THREAD

**Issue by tomleah** [appsody/website#67]
Define a release process and discuss how future releases are managed for each asset. We should produce a RELEASE.md that documents the process. The document should include:
- [ ] Instructions on how to make the asset available. (Does there need to be a GitHub release?)
- [ ] The definition of when the asset should be released? (Daily? When a feature is ready?)
- [ ] The dependencies on the asset being released. (Does the asset require another asset to be released beforehand or is it completely independent?)

**Comment by chilanti** [comment]
@tomleah - dependencies go both ways. Example: the Controller has no dependencies (i.e. it can be released by itself), but a new release of the controller almost for sure requires a new release of the CLI.

**Comment by chilanti** [comment]
How about this for headers:
# How to make this asset available
# Release schedule
# Dependencies
